experiment_number: '11'

environment:
  env_name: Pendulum-v1
  hardcore: False
  render_mode: rgb_array
  seed:   # Empty for random seed, makes the experiment "non-deterministic"
  image_processing: False
  image_size: 
  stack_frames:

agent:
  hidden_units: [128, 128]
  conv_layers:
  log_std_interval: [-20, 2]
  gamma: 0.99
  load_best: False 
  replay_buffer_size: 100000
  batch_size: 64
  
  init_temperature: 0.2
  actor_lr: 0.0003
  critic_lr: 0.003
  temperature_lr: 0.0003
  actor_update_freq: 2
  critic_target_update_freq: 2
  tau: 0.005

train: 
  gradient_steps: 1
  max_episodes: 400
  warmup_steps: 10000
  print_interval: 10
  checkpoint_interval: 50
  test_episodes: 25
  save_replay_buffer: False